title: HDL Batch Installer
description: A GUI for HDL-dump
markdown: GFM
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
github:
      zip_url: https://github.com/israpps/HDL-Batch-installer/releases
      tar_url: https://discord.gg/wczxvrkZk6
