blank_issues_enabled: true
contact_links:
  - name: discord server
    url: https://discord.gg/wczxvrkZk6
    about: our discord server
  - name: Official PSX-Place thread
    url: https://www.psx-place.com/resources/hdl-batch-installer.1173/
    about: Find more info or help here
