name: Database update request
description: Report a game ID missing in our database
title: "[Database Update]: "
labels: [Database Update]
assignees:
  - israpps
body:
  - type: markdown
    attributes:
      value: |
        Thanks for collaborating with our project! Please provide the following data:
        
  - type: input
    id: game-title
    attributes:
      label: Game title
      description: The original game title (if you know it)
      placeholder: Kingdom Hearts 2 - Final Mix
    validations:
      required: false
      
  - type: textarea
    id: game-id
    attributes:
      label: Game ID
      description: Provide the game ID! if you don´t know it open the game and provide the text inside the file called `system.cnf`
      placeholder: SLUS_123.45
      value: ""
    validations:
      required: true

  - type: textarea
    id: checksum
    attributes:
      label: game MD5 Checksum
      description: Please copy and paste the game MD5 checksum (if the game is in CD format you must get the checksum for the `.bin` file
      
  - type: checkboxes
    id: terms
    attributes:
      label: other checks
      description: check if necesary
      options:
        - label: I am using the [Latest version](https://github.com/israpps/HDL-Batch-installer/releases/)
