name: Discord webhook for tagged releases 
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  OPL-Release_webhook:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Discord Webhook tagged release
        uses: tsickert/discord-webhook@v2.0.2
        with:
          webhook-url: ${{ secrets.TESTERS_WEBHOOK }}
          content: "Hey <@everyone>! **HDL Batch installer**  **${{ env.RELEASE_VERSION }}** has been released! \\n - \\n \\n **Download:** \\n https://github.com/israpps/HDL-Batch-installer/releases/tag/${{ env.RELEASE_VERSION }} "

