name: Discord webhook for tagged releases 
on:
  workflow_dispatch:
  release:
    types: [released]
jobs:
  OPL-Release_webhook:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Set env
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Test
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Discord Webhook, tagged release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: tsickert/discord-webhook@v2.0.2
      with:
        webhook-url: ${{ secrets.TESTERS_WEBHOOK }}
        content: "Hey everyone! **HDL Batch installer**  **${{ env.RELEASE_VERSION }}** has been released! \\n - \\n <@&859615291477590046> ,"

