name: Update HDL dump

on:
  workflow_dispatch:
  repository_dispatch:
    types: [HDL_Dump_Updated]

jobs:
  rewrite-jsom:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Latest HDL-Dump
      run: |
        cd Release
        wget https://github.com/israpps/hdl-dump/releases/download/hdlinst/HDL.EXE -O $PWD/HDL.EXE
    
    
    - uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Update HDL dump to israpps/hdl-dump@${{ github.event.client_payload.sha }}'

    - name: trigger israpps auto-update system
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: peter-evans/repository-dispatch@v1
      with:
          token: ${{ secrets.IUS }}
          repository: israpps/HDL-Batch-installer
          event-type: HDL_Dump_Updated_
          client-payload: '{"sha": "${{ github.sha }}"}'
